import Header from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const roboto = Roboto({ weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
